# Form implementation generated from reading ui file 'designer.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(504, 332)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(150, 50, 181, 121))
        self.label.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.label.setObjectName("label")
        self.start_btn = QtWidgets.QPushButton(parent=Form)
        self.start_btn.setGeometry(QtCore.QRect(40, 220, 88, 25))
        self.start_btn.setObjectName("start_btn")
        self.stop_btn = QtWidgets.QPushButton(parent=Form)
        self.stop_btn.setGeometry(QtCore.QRect(240, 220, 88, 25))
        self.stop_btn.setObjectName("stop_btn")
        # test code
        # self.start_btn.clicked.connect(self.Test)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    # def Test(self):
    #     self.label.setText('Clicked')
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "TextLabel"))
        self.start_btn.setText(_translate("Form", "start"))
        self.stop_btn.setText(_translate("Form", "stop"))



